image: node:14.16.1-alpine3.13

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline
  - npm install

pages:
  stage: deploy
  script:
    - npx ng build --prod --base-href=/ear-sharpener/
    - echo "$(ls -la)"
    - mkdir public
    - cp -r dist/MusicTrainer/* public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
